### ISSUE TITLE
Figure out why gdc has 2 gcq objects (1 final/1 unassigned until later)

### ISSUE THREAD

**Issue by tran-brian** [KHikami/ProjectFiCallingDeciphered#25]
final gcq c calls gcq non-static methods, but can't find declaration

**Comment by tran-brian** [comment]
Found the declaration in the constructor to the one passed in.

**Comment by wminner** [comment]
I believe the final gcq (this.c) is the current Connection object, and the other (this.g) is created when handoff actually occurs (so it would be the new Connection object).
